actors:
  nagisa:
    image_url: /images/actors/naginagisa.png
    name: NagiNagisa
    url: https://twitter.com/nagi_nagisachan

author: NagiNagisa
description: Vの裏側 なぎなぎラジオは、技術系・将棋系、個人Vtuberの私が気になったVtuber関連ニュース、VR技術、近況などを語るポッドキャストです。
description_long: Vの裏側 なぎなぎラジオは、技術系・将棋系、個人Vtuberの私が気になったVtuber関連ニュース、VR技術、近況などを語るポッドキャストです。
email: naginagisachan@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: nagiradio
itunes_podcast_url:
keywords: podcast,vtuber,エンジニア,プログラマ,VR
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Vの裏側 なぎなぎラジオ
url: https://naginagisa.github.io/NagiRadio/